### ISSUE TITLE
关于SQL注入的一些解释

### ISSUE THREAD

**Issue by QAQ114514** [BytedanceCamp-404NotFound/SimpleTikTok#39]
关于程序的SQL注入问题，Gorm框架语言自带了预编译功能，可以避免SQL注入，因此注意以下三点：
1、不要使用dao.db.Raw(sql)查询
2、不要直接使用fmt.Sprintf执行SQL语句
3、避免在查询过程中使用字符串拼接

**Comment by gtoo8888** [comment]
可以提交到
https://github.com/BytedanceCamp-404NotFound/ShareEnv
作为代码规范
