### ISSUE TITLE
/douyin/feed视频流接口的一个大问题

### ISSUE THREAD

**Issue by XiaoKabuDa** [BytedanceCamp-404NotFound/SimpleTikTok#63]
现在 /douyin/feed 视频流接口必须传入token，才会返回视频列表，没有传token时直接是返回错误

但抖声app在没有登陆账号的情况下，允许用户观看视频，且不会给feed接口传token

这会导致刚打开app时(如果没有登陆账号)，软件直接报错，只有登陆上去后，才能观看视频

**Comment by gtoo8888** [comment]
还需要明确token的作用，现在不知道是否登录对刷视频有什么影响？感觉没有影响

**Comment by gtoo8888** [comment]
已经修复，重新修改了feed接口的逻辑
